# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_add_month_year_to_salary_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='van_child_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
