# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_van_child_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='security_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deduction amount per employee', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='van_child_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Van/Child deduction amount per employee', max_digits=12),
        ),
    ]
