# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_security_van_child_to_salary_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryconfig',
            old_name='security_amount',
            new_name='security_pct',
        ),
        migrations.RenameField(
            model_name='salaryconfig',
            old_name='van_child_amount',
            new_name='van_child_pct',
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='security_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deduction % of basic', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='van_child_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Van/Child deduction % of basic', max_digits=5),
        ),
    ]
