# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_rename_security_van_child_to_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='use_custom_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_housing_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_medical_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_transport_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_fuel_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_pf_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_security_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_van_child_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_bonus_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_bonus_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
