# Generated by Django 6.0.1 on 2026-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_monthlysalary_has_custom_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='new_employee_security_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Security deduction % of basic for first 2 months after joining', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='security_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deduction % of basic (normal, from 3rd month)', max_digits=5),
        ),
    ]
