# Generated by Django 6.0.1 on 2026-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_monthlysalary_has_custom_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='probation_security_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Security deduction % of basic during first 2 months (probation)', max_digits=5),
        ),
    ]
