# Generated by Django 6.0.1 on 2026-08-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_teacherprofile_bank_account_teacherprofile_bank_name_and_more'),
        ('hr', '0012_add_new_employee_security_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_date', models.DateField()),
                ('last_working_date', models.DateField()),
                ('separation_reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('contract_end', 'End of Contract'), ('retirement', 'Retirement'), ('other', 'Other')], default='resignation', max_length=20)),
                ('separation_reason_detail', models.TextField(blank=True, default='')),
                ('security_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit deduction on exit', max_digits=12)),
                ('last_salary_withheld', models.BooleanField(default=False, help_text='Was last salary withheld?')),
                ('last_salary_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount of withheld last salary', max_digits=12)),
                ('additional_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Any other deductions on exit', max_digits=12)),
                ('deduction_reason', models.TextField(blank=True, default='', help_text='Reason for additional deductions')),
                ('clearance_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separation_record', to='academics.teacherprofile')),
            ],
        ),
    ]
