# Generated by Django 6.0.2 on 2026-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_separationrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='custom_fuel_pct',
            new_name='custom_kid_fee_pct',
        ),
        migrations.RenameField(
            model_name='employeesalary',
            old_name='fuel_allowance',
            new_name='kid_fee',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='cfg_fuel_pct',
            new_name='cfg_kid_fee_pct',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='fuel_allowance',
            new_name='kid_fee',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='fuel_allowance_pct',
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='kid_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Kid's fee allowance % of basic", max_digits=5),
        ),
    ]
