# Generated by Django 6.0.2 on 2026-08-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_rename_custom_fuel_pct_employeesalary_custom_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='custom_kid_fee_pct',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='kid_fee',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='cfg_kid_fee_pct',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='kid_fee',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='kid_fee_pct',
        ),
    ]
