# Generated by Django 6.0.2 on 2026-08-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_remove_employeesalary_custom_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='cfg_kid_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='cfg_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', help_text='Mode used when this record was saved: percentage or amount', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='kid_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='config_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', help_text='All salary fields use percentage or fixed amount', max_length=10),
        ),
    ]
