# Generated by Django 6.0.2 on 2026-08-29 07:20
# Modified: AddField ops replaced with RunSQL IF NOT EXISTS for idempotency

from django.db import migrations, models


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    vendor = conn.vendor
    with conn.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_monthlysalary'")
            existing = {row[0] for row in cursor.fetchall()}
            if 'cfg_kid_fee_pct' not in existing:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kid_fee_pct numeric(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_mode' not in existing:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kid_fee' not in existing:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kid_fee numeric(12,2) DEFAULT 0 NOT NULL")
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_salaryconfig'")
            existing = {row[0] for row in cursor.fetchall()}
            if 'config_mode' not in existing:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN config_mode varchar(10) DEFAULT 'percentage' NOT NULL")
        else:
            cursor.execute("PRAGMA table_info(hr_monthlysalary)")
            cols = {row[1] for row in cursor.fetchall()}
            if 'cfg_kid_fee_pct' not in cols:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kid_fee_pct decimal(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_mode' not in cols:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kid_fee' not in cols:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kid_fee decimal(12,2) DEFAULT 0 NOT NULL")
            cursor.execute("PRAGMA table_info(hr_salaryconfig)")
            cols = {row[1] for row in cursor.fetchall()}
            if 'config_mode' not in cols:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN config_mode varchar(10) DEFAULT 'percentage' NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_ensure_config_mode_columns'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_bonus_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_housing_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_medical_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_pf_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_security_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_transport_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='custom_van_child_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_bonus_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_housing_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_medical_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_pf_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_security_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_transport_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='cfg_van_child_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Or bonus as % of basic (if per_day=0)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='housing_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Housing allowance % of basic', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='medical_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Medical allowance % of basic', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='new_employee_security_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Security deduction % of basic for first 2 months after joining', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='provident_fund_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PF % of basic', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='security_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deduction % of basic (normal, from 3rd month)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax % deducted from gross', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='transport_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport allowance % of basic', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='van_child_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Van/Child deduction % of basic', max_digits=12),
        ),
    ]
