# Generated by Django 6.0.2 on 2026-08-29 08:25
# Modified: AddField ops use RunPython for idempotency (SQLite + PostgreSQL)

from django.db import migrations, models


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    vendor = conn.vendor
    with conn.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_monthlysalary'")
            existing = {row[0] for row in cursor.fetchall()}
            if 'cfg_kids_education_pct' not in existing:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kids_education_pct numeric(12,2) DEFAULT 0 NOT NULL")
            if 'kids_education_allowance' not in existing:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kids_education_allowance numeric(12,2) DEFAULT 0 NOT NULL")
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_salaryconfig'")
            existing = {row[0] for row in cursor.fetchall()}
            if 'kids_education_pct' not in existing:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN kids_education_pct numeric(12,2) DEFAULT 0 NOT NULL")
        else:
            cursor.execute("PRAGMA table_info(hr_monthlysalary)")
            cols = {row[1] for row in cursor.fetchall()}
            if 'cfg_kids_education_pct' not in cols:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kids_education_pct decimal(12,2) DEFAULT 0 NOT NULL")
            if 'kids_education_allowance' not in cols:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kids_education_allowance decimal(12,2) DEFAULT 0 NOT NULL")
            cursor.execute("PRAGMA table_info(hr_salaryconfig)")
            cols = {row[1] for row in cursor.fetchall()}
            if 'kids_education_pct' not in cols:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN kids_education_pct decimal(12,2) DEFAULT 0 NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_monthlysalary_cfg_kid_fee_pct_monthlysalary_cfg_mode_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
