# Generated by Django 6.0.1 on 2026-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_monthlysalary_cfg_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='cfg_kid_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='cfg_kids_education_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='cfg_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', help_text='Mode used when this record was saved: percentage or amount', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='kid_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='kids_education_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='config_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', help_text='All salary fields use percentage or fixed amount', max_length=10),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='kids_education_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kids education allowance % of basic', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grand total accumulated deductions', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_other',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total other deductions', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_pf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total provident fund deducted', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_security',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total security deducted', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax deducted', max_digits=12),
        ),
        migrations.AddField(
            model_name='separationrecord',
            name='total_van_child',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total van/child deducted', max_digits=12),
        ),
    ]
