# Generated by Django 6.0.2 on 2026-08-29
# Fixed: Use RunPython for idempotency to avoid conflicts with 0019/0020

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Add columns idempotently — 0019/0020 may have already added some."""
    conn = schema_editor.connection
    vendor = conn.vendor
    with conn.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_monthlysalary'")
            existing_ms = {row[0] for row in cursor.fetchall()}
            if 'cfg_kid_fee_pct' not in existing_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kid_fee_pct numeric(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_kids_education_pct' not in existing_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kids_education_pct numeric(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_mode' not in existing_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kid_fee' not in existing_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kid_fee numeric(12,2) DEFAULT 0 NOT NULL")
            if 'kids_education_allowance' not in existing_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kids_education_allowance numeric(12,2) DEFAULT 0 NOT NULL")

            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_salaryconfig'")
            existing_sc = {row[0] for row in cursor.fetchall()}
            if 'config_mode' not in existing_sc:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN config_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kids_education_pct' not in existing_sc:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN kids_education_pct numeric(12,2) DEFAULT 0 NOT NULL")

            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='hr_separationrecord'")
            existing_sep = {row[0] for row in cursor.fetchall()}
            if 'total_pf' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_pf numeric(12,2) DEFAULT 0 NOT NULL")
            if 'total_security' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_security numeric(12,2) DEFAULT 0 NOT NULL")
            if 'total_tax' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_tax numeric(12,2) DEFAULT 0 NOT NULL")
            if 'total_van_child' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_van_child numeric(12,2) DEFAULT 0 NOT NULL")
            if 'total_other' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_other numeric(12,2) DEFAULT 0 NOT NULL")
            if 'total_deductions' not in existing_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_deductions numeric(12,2) DEFAULT 0 NOT NULL")
        else:
            cursor.execute("PRAGMA table_info(hr_monthlysalary)")
            cols_ms = {row[1] for row in cursor.fetchall()}
            if 'cfg_kid_fee_pct' not in cols_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kid_fee_pct decimal(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_kids_education_pct' not in cols_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_kids_education_pct decimal(12,2) DEFAULT 0 NOT NULL")
            if 'cfg_mode' not in cols_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN cfg_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kid_fee' not in cols_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kid_fee decimal(12,2) DEFAULT 0 NOT NULL")
            if 'kids_education_allowance' not in cols_ms:
                cursor.execute("ALTER TABLE hr_monthlysalary ADD COLUMN kids_education_allowance decimal(12,2) DEFAULT 0 NOT NULL")

            cursor.execute("PRAGMA table_info(hr_salaryconfig)")
            cols_sc = {row[1] for row in cursor.fetchall()}
            if 'config_mode' not in cols_sc:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN config_mode varchar(10) DEFAULT 'percentage' NOT NULL")
            if 'kids_education_pct' not in cols_sc:
                cursor.execute("ALTER TABLE hr_salaryconfig ADD COLUMN kids_education_pct decimal(12,2) DEFAULT 0 NOT NULL")

            cursor.execute("PRAGMA table_info(hr_separationrecord)")
            cols_sep = {row[1] for row in cursor.fetchall()}
            if 'total_pf' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_pf decimal(12,2) DEFAULT 0 NOT NULL")
            if 'total_security' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_security decimal(12,2) DEFAULT 0 NOT NULL")
            if 'total_tax' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_tax decimal(12,2) DEFAULT 0 NOT NULL")
            if 'total_van_child' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_van_child decimal(12,2) DEFAULT 0 NOT NULL")
            if 'total_other' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_other decimal(12,2) DEFAULT 0 NOT NULL")
            if 'total_deductions' not in cols_sep:
                cursor.execute("ALTER TABLE hr_separationrecord ADD COLUMN total_deductions decimal(12,2) DEFAULT 0 NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_monthlysalary_cfg_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
