# Generated by Django 6.0.2 on 2026-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_monthlysalary_cfg_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='pf_administration_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Provident Fund % for Administration', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='pf_janitorial_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund % for Janitorial', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='pf_management_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Provident Fund % for Management Staff', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='pf_teacher_pct',
            field=models.DecimalField(decimal_places=2, default='7.50', help_text='Provident Fund % for Teachers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='provident_fund_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PF % of basic (legacy fallback)', max_digits=12),
        ),
    ]
