# Generated by Django 6.0.2 on 2026-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_monthlysalary_cfg_kid_fee_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLetterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bank_islami', 'Bank Islami'), ('ubl', 'UBL'), ('cash', 'Cash in Hand'), ('personal', 'Personal Account')], max_length=20, unique=True)),
                ('recipient_header', models.TextField(blank=True, default='', help_text='Addressed-to block, e.g. The Manager, Bank Name, Branch, City.')),
                ('subject', models.CharField(default='TRANSFER OF OFFICERS / STAFF PAY', max_length=200)),
                ('signature_name', models.CharField(default='CEO', max_length=100)),
                ('signature_org', models.CharField(default='Royal International School System', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
