# Generated by Django 6.0.2 on 2026-10-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_bankletterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankletterconfig',
            name='body_content',
            field=models.TextField(blank=True, default='', help_text='Letter body. Placeholders: {cheque_no} {dated} {dated_long} {release_date} {amount} {amount_words} {month} {year}'),
        ),
        migrations.AddField(
            model_name='bankletterconfig',
            name='cheque_no',
            field=models.CharField(blank=True, default='', help_text='Cheque number used in the letter body. Leave blank for cash letters.', max_length=50),
        ),
    ]
