# Generated by Django 6.0.2 on 2026-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_school_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmanager',
            name='can_manage_hr_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('admin_manager', 'Admin Manager'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
    ]
