# Generated by Django 6.0.2 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminmanager_can_manage_hr_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmanager',
            name='can_view_edit_employees',
            field=models.BooleanField(default=False),
        ),
    ]
