# Generated by Django 6.0.2 on 2026-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_teacherprofile_bank_account_teacherprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='documents',
            field=models.FileField(blank=True, help_text='Upload staff documents (PDF, JPG, PNG)', null=True, upload_to='teachers/documents/'),
        ),
    ]
