# Generated by Django 6.0.2 on 2026-08-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_teacherprofile_bank_account_teacherprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_content', models.TextField(help_text='Base64 encoded file content')),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='academics.teacherprofile')),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
