# Generated by Django 6.0.2 on 2026-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_teacherprofile_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='documents',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='documents_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of staff documents'),
        ),
    ]
