# Generated by Django 6.0.2 on 2026-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_teacherprofile_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='husband_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='husband_cnic',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='husband_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='husband_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='kids_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of kids: [{"name":"...","dob":"YYYY-MM-DD","gender":"M/F"}]'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
    ]
