# Generated by Django 6.0.1 on 2026-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_teacherprofile_husband_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('vp', 'VP'), ('group_head', 'Group Head'), ('section_head', 'Section Head'), ('assistant_manager', 'Assistant Manager'), ('a_coordinator', 'A. Coordinator'), ('accountant', 'Accountant'), ('team_lead', 'Team Leader'), ('fdc', 'F.D.C'), ('compositer', 'Compositer'), ('aya', 'Aya'), ('photocopier', 'Photocopier'), ('office_boy', 'Office Boy'), ('sweeper', 'Sweeper')], default='teacher', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('single_parent', 'Single Parent')], default='single', max_length=20),
        ),
    ]
