# Generated by Django 6.0.2 on 2026-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_teacherprofile_husband_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('vp', 'VP'), ('group_head', 'Group Head')], default='teacher', max_length=50),
        ),
    ]
