# Generated by Django 6.0.2 on 2026-09-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_teacherprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='num_children',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of children (for non-single females)'),
        ),
    ]
