# Generated by Django 6.0.2 on 2026-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_add_num_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
