# Generated by Django 6.0.2 on 2026-09-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('manager_academics', 'Manager Academics'), ('hr_manager', 'HR Manager'), ('director', 'Director'), ('vp', 'VP'), ('group_head', 'Group Head'), ('section_head', 'Section Head'), ('assistant_manager', 'Assistant Manager'), ('assistant_manager_academics', 'Assistant Manager Academics'), ('a_coordinator', 'A. Coordinator'), ('accountant', 'Accountant'), ('team_lead', 'Team Leader'), ('fdc', 'F.D.C'), ('compositer', 'Compositer'), ('aya', 'Aya'), ('photocopier', 'Photocopier'), ('office_boy', 'Office Boy'), ('sweeper', 'Sweeper')], default='teacher', max_length=30),
        ),
    ]
