# Generated by Django 6.0.2 on 2026-10-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_teacherprofile_designation'),
        ('academics', '0015_alter_teacherprofile_designation'),
    ]

    operations = [
    ]
